spring.application.name=dksa-backend







spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require

spring.datasource.username=postgres.sndnsrjyyaqkedddlhir
spring.datasource.password=Dksa@2026#123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect










server.port=${PORT:8080}


jwt.secret=MySecretKeyForDKSACricketBookingSystem2026MySecretKey
jwt.expiration=86400000


razorpay.key.id=rzp_live_SnAI8KaBQOwiqa

razorpay.key.secret=rzp_live_SnAI8KaBQOwiqa


cloudinary.cloud-name=dnnt2mh1g

cloudinary.api-key=227839961322457

cloudinary.api-secret=Wtg3efAyr0YWEw8x0G1FSB6rdq8









spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=vamsibilla248@gmail.com

spring.mail.password=313305vamsibilla

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true


spring.profiles.active=prod